### ISSUE TITLE
Can't make it work on Cordova Android

### ISSUE THREAD

**Issue by jay34fr** [PeterHdd/cordova-plugin-crypto-file#12]
Hi,

I have this config :
- Cordova 9 (not ionic)
- Android 8.1.0
- iOS 5.0.1

I installed the plugin, it works perfectly on iOS, the sources are crypted and decrypted on installation.

But on Android, all the sources are well crypted but not all seems decrypted.
I think there is an issue when the plugin try to decrypted the app.js or index.html

If anyone have an idea...

Thx

**Comment by domenicapg** [comment]
me too.
I fixed the program.
It's work in my project.

DecryptResource.java

1.Add Declaration
import java.util.regex.Pattern;

2.Replace Variable Declaration
  /*
  private static final String[] CRYPT_FILES = {
    ".htm",
    ".html",
    ".js",
    ".css",
  };
  */
  private static final String[] INCLUDE_FILES = new String[] { };
  private static final String[] EXCLUDE_FILES = new String[] { };

3.Replce Function
   /*
  private boolean isCryptFiles(String uri) {
    for (String ext: CRYPT_FILES) {
      if (uri.endsWith(ext)) {
        return true;
      }
    }
    return false;
  }
  */
  private boolean isCryptFiles(String uri) {
    String checkPath = uri.replace("file:///android_asset/www/", "");
    if (!this.hasMatch(checkPath, INCLUDE_FILES)) {
    return false;
    }
    if (this.hasMatch(checkPath, EXCLUDE_FILES)) {
      return false;
    }
    return true;
  }

  private boolean hasMatch(String text, String[] regexArr) {
    for (String regex : regexArr) {
      if (Pattern.compile(regex).matcher(text).find()) {
        return true;
      }
    }
    return false;
  }

**Comment by PeterHdd** [comment]
Hi, this plugin was created to work with the changes that were done on ionic webview, thats why you may be facing issues. Since ionic webview is now serving android content on http://localhost:8080 then to be able to encrypt and decrypt this plugin needs to serve content in the same url.

I'm not sure how it is in cordova alone, but if the app is not loading in the http://localhost:8080, then it is better to use the plugin:

https://github.com/tkyaji/cordova-plugin-crypt-file

(mentioned in the readme)
Note: the plugin might have some issues with cordova 9 since their was breaking changes, you can check the js file of this plugin to see the fixes.
