### ISSUE TITLE
BUG: Http call showing CORS policy: Response to preflight error

### ISSUE THREAD

**Issue by thomas550i** [PeterHdd/cordova-plugin-crypto-file#9]
**After installing plugin http ajax call gives cors error**

error : Access to XMLHttpRequest at 'http://xxx.com/Service.svc' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.

**Comment by jvcjunior** [comment]
Any news on this one? I'm facing the same problem. 

In my project, the assets are served by: `file:///android_asset/www/index.html`. When I installed this plugin is serving like: 'localhost:8080'.

Because of that, a CORS error is happening. My server does not allow requests from localhost. Before it was working. 

How can I make the assets to be served as file:// again?

**Comment by zezelazo** [comment]
@jvcjunior you can add  `<allow-navigation href="*://localhost:8080/*" />` to your **config.xml** the problem i got here was the white list plugin was blocking the requests, i saw it on logcat

**Comment by PeterHdd** [comment]
This plugin I created it to work with the ionic webview, because last year ionic did some changes and made the ionic webview to serve the app on http://localhost:8080 thats why  when you install this plugin it is also serving on localhost:8080 so it can work with the changes in webview:

https://github.com/ionic-team/cordova-plugin-ionic-webview/blob/master/CHANGELOG.md#200-2018-07-23

If you are not using ionic but want to encrypt your code, it is better to use:

https://github.com/tkyaji/cordova-plugin-crypt-file

(that is referenced in the readme)
Note: the `cordova-plugin-crypt-file` might have some issues that are fixed in the javascript file of this plugin
